/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.63
 * Generated at: 2017-08-29 06:51:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.io.*;
import java.util.*;
import java.text.SimpleDateFormat;
import java.util.Date;

public final class showplan_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<span style=\"font-size:12px;\">\r\n");
      out.write("<span style=\"font-size:14px;\">\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("\r\n");
      out.write("创建计划表\r\n");
      out.write("create database person;\r\n");
      out.write("use person;\r\n");
      out.write("create table plan(\r\n");
      out.write("id                 int primary key auto_increment  COMMENT 'id号',\r\n");
      out.write("plan_name          varchar(1024) not null          COMMENT '计划（任务）名称',\r\n");
      out.write("datenum_consuming  int(50) not null                COMMENT '耗时（天）',\r\n");
      out.write("datenum_interval   int(50) not null                COMMENT '间隔（天）',\r\n");
      out.write("lastdate_review    date not null                   COMMENT '上次复习日期',\r\n");
      out.write("nextdate_review    date not null                   COMMENT '下次复习日期',\r\n");
      out.write("date_calculate     date not null                   COMMENT '计算时的日期',\r\n");
      out.write("byy                varchar(20480)                  COMMENT '备注',\r\n");
      out.write("importance         int(1) not null                 COMMENT '重要性',\r\n");
      out.write("count_review       int(50) not null                COMMENT '复习次数',\r\n");
      out.write("complete_flag      int(1) not null                 COMMENT '完成情况,0-未完成，1-完成'\r\n");
      out.write(");\r\n");
      out.write("\r\n");
      out.write("alter table plan modify lastdate_review date default '2001-01-01';\r\n");
      out.write("alter table plan modify nextdate_review date default '2001-01-01';\r\n");
      out.write("alter table plan modify date_calculate date default '2001-01-01';\r\n");
      out.write("alter table plan modify count_review int(50) default 0;\r\n");
      out.write("\r\n");
      out.write("alter table plan modify importance  int(10) not null COMMENT '重要性';\r\n");
      out.write("alter table plan modify complete_flag  int(10) not null COMMENT '完成情况';\r\n");
      out.write("alter table plan add emergency int(10) not null COMMENT '紧急性';\r\n");
      out.write("\r\n");
      out.write("create table operation_record(\r\n");
      out.write("keystring      varchar(10) primary key not null    COMMENT 'key的值',\r\n");
      out.write("valuestring    varchar(255) not null               COMMENT 'value的值',\r\n");
      out.write("plan_data      date                                COMMENT '日期',\r\n");
      out.write("byy            varchar(1024) not null              COMMENT '备注'\r\n");
      out.write(");\r\n");
      out.write("\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\ttable {\r\n");
      out.write("\t\tborder: 2px #CCCCCC solid;\r\n");
      out.write("\t\twidth: 90%;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\ttd,th {\r\n");
      out.write("\t\theight: 30px;\r\n");
      out.write("\t\tborder: #CCCCCC 1px solid;\r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<title>日常规划计划</title>\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		//当天日期
		Date dt=new Date();
		SimpleDateFormat matter1=new SimpleDateFormat("yyyy-MM-dd");
		String rq=matter1.format(dt);
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");

		//驱动程序名
		String driverName = "com.mysql.jdbc.Driver";
		//数据库用户名
		String userName = "root";
		//密码
		String userPasswd = "q";
		//数据库名
		String dbName = "person";
		//表名
		String tableName = "plan";
		//连接字符串
		String url = "jdbc:mysql://localhost:3306/" + dbName + "?user="
				+ userName + "&password=" + userPasswd;  
		Class.forName("com.mysql.jdbc.Driver").newInstance();
		Connection connection = DriverManager.getConnection(url);
		Statement statement = connection.createStatement();

		/*
		如果下次复习的时间 小于 当前日期，
		则更新 上次复习的日期，规则: 上次复习日期=下次复习日期。
		SQL语句如下：
		update plan set lastdate_review=nextdate_review 
		where nextdate_review < (select date_format(now(),'%Y-%m-%d'));
		*/
		statement.executeUpdate( "update plan set lastdate_review= " +
				"nextdate_review " +
				"where nextdate_review < (select date_format(now(),'%Y-%m-%d'));" );

		/*
		如果下次复习的时间 小于 当前日期，
		则更新 下次复习的日期、复习次数，规则: 下次复习日期=上次复习日期 + 间隔天数 + 耗时天数 - 1;
			复习次数 = 复习次数 + 1。
		SQL语句如下：
		update plan set nextdate_review=DATE_ADD( lastdate_review, INTERVAL (datenum_interval+datenum_consuming - 1) DAY),
		count_review=count_review+1
		where nextdate_review < (select date_format(now(),'%Y-%m-%d'));
		*/
		statement.executeUpdate( "update plan set nextdate_review= " +
			"DATE_ADD( lastdate_review, INTERVAL (datenum_interval+datenum_consuming) DAY), " +
			"count_review=count_review+1 " +
			"where nextdate_review < (select date_format(now(),'%Y-%m-%d'));" );

		ResultSet rst = statement.executeQuery("select * from operation_record " +
			"where plan_data = '"+rq+"' and keystring='XCFXRQJS' " );
		String sUpdateCompFlag = "";
		while (rst.next())
		{
			sUpdateCompFlag = rst.getString(2);
		}
		
		if(!sUpdateCompFlag.trim().equals("1") )
		{
			/*
			整个表中数据更新为未完成
			SQL语句如下:
			update plan set complete_flag=0;
			*/
			statement.executeUpdate( "update plan set complete_flag=0;" );
			
			/*
			更新operation_record表中的相关字段
			*/
			statement.executeUpdate( "update operation_record set valuestring='1',plan_data='"+rq+"' " );
		}
		
		/*
		查询plan表中的数据
		当日的任务  and 复习正在进行中任务
		*/
		ResultSet rs = statement.executeQuery("SELECT plan_name,datenum_consuming,datenum_interval,lastdate_review,byy,importance,count_review,complete_flag,id,emergency " +
			"FROM plan where ( nextdate_review='"+rq+"' ) or " +
			" ( DATE_ADD( lastdate_review, INTERVAL datenum_consuming DAY ) >= '"+rq+"' ) order by complete_flag asc,importance desc,emergency desc");
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<input type=\"button\" value=\"添加\" onclick=\"window.open('insertplan.jsp','_blank','height=450,width=800')\">\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\t<form action=\"UpdatePlanFinishFlagServlet\">\r\n");
      out.write("\t\t<table border=\"0\"  align=\"center\" width=\"100%\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t<div class=\"text\" style=\" text-align:right;\">重要性：3非常重要，2比较重要，1一般重要；急：    3非常急  ，2比较急  ，1一般急  。</div>\r\n");
      out.write("\t\t\t\t<div class=\"text\" style=\" text-align:right;\">严格按照这个顺序来做，做完第一件事情，再做第二件。</div>\r\n");
      out.write("\t\t\t\t</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t<table align=\"center\" width=\"100%\">\r\n");
      out.write("\t\t<tr><th colspan=\"11\" >今日计划规划</th></tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>\r\n");
      out.write("\t\t\t\t");

					out.print("计划（任务）名称");
				
      out.write("\r\n");
      out.write("\t\t\t</th>\r\n");
      out.write("\t\t\t<th>\r\n");
      out.write("\t\t\t\t");

					out.print("耗时（天）");
				
      out.write("\r\n");
      out.write("\t\t\t</th>\r\n");
      out.write("\t\t\t<th>\r\n");
      out.write("\t\t\t\t");

					out.print("间隔（天）");
				
      out.write("\r\n");
      out.write("\t\t\t</th>\r\n");
      out.write("\t\t\t<th>\r\n");
      out.write("\t\t\t\t");

					out.print("上次复习日期");
				
      out.write("\r\n");
      out.write("\t\t\t</th>\r\n");
      out.write("\t\t\t<th>\r\n");
      out.write("\t\t\t\t");

					out.print("备注说明");
				
      out.write("\r\n");
      out.write("\t\t\t</th>\r\n");
      out.write("\t\t\t<th>\r\n");
      out.write("\t\t\t\t");

					out.print("重要性");
					/*
						重要性：3非常重要，2比较重要，1一般重要
					*/
				
      out.write("\r\n");
      out.write("\t\t\t</th>\r\n");
      out.write("\t\t\t<th>\r\n");
      out.write("\t\t\t\t");

					out.print("紧急性");
					/*
						紧急性： 3非常急  ，2比较急  ，1一般急 
					*/
				
      out.write("\r\n");
      out.write("\t\t\t<th>\r\n");
      out.write("\t\t\t\t");

					out.print("复习次数");
				
      out.write("\r\n");
      out.write("\t\t\t</th>\r\n");
      out.write("\t\t\t<th>\r\n");
      out.write("\t\t\t\t");

					out.print("完成情况");
				
      out.write("\r\n");
      out.write("\t\t\t</th>\r\n");
      out.write("\t\t\t<th>\r\n");
      out.write("\t\t\t\t");

					out.print("完成情况更新");
				
      out.write("\r\n");
      out.write("\t\t\t</th>\r\n");
      out.write("\t\t\t<th>\r\n");
      out.write("\t\t\t\t");

					out.print("修改");
				
      out.write("\r\n");
      out.write("\t\t\t</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t");

			while (rs.next())
			{
		
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"20%\">\r\n");
      out.write("\t\t\t\t");

					out.print(rs.getString(1).replaceAll("\r\n", "<br>"));
				
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"3%\">\r\n");
      out.write("\t\t\t\t");

					out.print(rs.getString(2));
				
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"3%\">\r\n");
      out.write("\t\t\t\t");

					out.print(rs.getString(3));
				
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"10%\">\r\n");
      out.write("\t\t\t\t");

					out.print(rs.getString(4));
				
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"35%\">\r\n");
      out.write("\t\t\t\t");

					out.print(rs.getString(5).replaceAll("\r\n", "<br>"));
				
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"2.5%\">\r\n");
      out.write("\t\t\t\t");

					out.print(rs.getString(6));
				
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"2.5%\">\r\n");
      out.write("\t\t\t\t");

					out.print(rs.getString(10));
				
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"4%\">\r\n");
      out.write("\t\t\t\t");

					out.print(rs.getString(7));
				
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"4%\">\r\n");
      out.write("\t\t\t\t");

					String sFinishFlag = rs.getString(8);
					if ( sFinishFlag.equals( "0" ) )
					{
						out.print( "未完" );
					}
					else if ( sFinishFlag.equals( "1" ) )
					{
						out.print( "完成" );
					}
					else
					{
						out.print( "未知" );
					}
				
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"10%\">\r\n");
      out.write("\t\t\t\t<!-- input type=\"radio\" name=\"finishflag\" value=\"0\" onclick=\"getSex()\" checked=\"checked\" -->\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"finishflag\" value=\"0|");
 out.print(rs.getString(9));
      out.write("\" onclick=\"javascript:form.submit();\" checked=\"checked\">未完\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- input type=\"radio\" name=\"finishflag\" value=\"1\" onclick=\"update_complete_flag(rs.getString(9), 1)\" -->\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"finishflag\" value=\"1|");
 out.print(rs.getString(9));
      out.write("\" onclick=\"javascript:form.submit();\">完成\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"修改\" onclick=\"window.open('updateplan.jsp?id=");
 out.print(rs.getString(9));
      out.write("&plan_name=");
 out.print(rs.getString(1).replaceAll("\r\n", "<br>"));
      out.write("&datenum_consuming=");
 out.print(rs.getString(2));
      out.write("&datenum_interval=");
 out.print(rs.getString(3));
      out.write("&byy=");
 out.print(rs.getString(5).replaceAll("\r\n", "<br>"));
      out.write("&importance=");
 out.print(rs.getString(6));
      out.write("&emergency=");
 out.print(rs.getString(10));
      out.write("&complete_flag=");
 out.print(rs.getString(8));
      out.write("','_blank','height=450,width=800')\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("            <th colspan=\"9\">\r\n");
      out.write("\t\t\t<p align=\"center\">数据查询完成!</p>\r\n");
      out.write("\t\t\t</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<!-- div align=\"center\">\r\n");
      out.write("\t\t");

			out.print("数据查询完成！");
		
      out.write("\r\n");
      out.write("\t</div-->\r\n");
      out.write("\t");

		rst.close();
		rs.close();
		statement.close();
		connection.close();
	
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("</span>\r\n");
      out.write("\t<span style=\"font-size:24px;color: rgb(255, 0, 0);\"></span>\r\n");
      out.write("</span>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
